### ISSUE TITLE
Using a different port for Pentaho from 8080

### ISSUE THREAD

**Issue by fcorti** [fcorti/Alflytics#6]
Some errors appear using a different port for installation than 8080.

**Comment by yregaieg** [comment]
Did you try configuring the connector in server.xml ? only then it works for me behind reverse proxy and/or different port

**Comment by fcorti** [comment]
I did not tried, fwu submitted this issue and he is trying to fix it in his Windows environment.
We agreed that he will push the fix if he will succeed.
I asked him a git user to include him in the discussion.

**Comment by smvo** [comment]
hello,

Sorry but the problem was not related with errors and the 8080 port! The problem is that the 8080 port is fixed in a lot of places inside Alflytics files. Thus, it is not easy to set another port, other than 8080. For me this would be important because Im running Alfresco on the same machine, which by default also use 8080 port. Finally, it is not only the 8080 port that needs to be changed. There are other ports that will collide when using penthao and Alfresco on the same machine. 

What I did was to change the Alfresco ports. Changing it on Alflytics side would mean to edit some files.

I dont have sure if it will be easy to set the ports on the Alflytics side in just one file, but if not, at least would be great to inform new users the need to change the ports when running both Pentaho and Alfresco on the same machine. The users could be inform in the manual, maybe?

regards,

Sérgio

**Comment by fcorti** [comment]
Thank you for your patience guys.
I had the change to go through this issue and updated the distribution package.
I also added a new FAQ to the documentation to describe a side effect that can happen choosing a different port (or URL) from the default one.

Closing the issue.
